QSource/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),    
    
    #Do not do this for production!!! This is only used for development environment
    url(r'^$', 'qsource_user.views.home', name='home'),
    url(r'^contact/$', 'qsource_user.views.contact', name='contact'),
    url(r'^about/$', 'qsource_user.views.about', name='about'),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

polls/urls.py
from django.conf.urls import url

from . import views 

# Regular expressions that determine the possible patterns that a URL can match.
# If a URL matches one of the given patterns, the appropriate method is called.
urlpatterns = [
    
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^question/$', views.GetQuestion, name='question'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^settings/$', views.settings, name='settings')

]

polls/models.py
import datetime
from django.utils import timezone
from django.db import models

# The Question model represents a poll with question, answers, and votes. It has
# a many-to-many relationship with the UserData model. See
# qsource-user/models.py to see the details of the UserData model
# implementation.
class Question(models.Model):
    # Basic poll information.
    question_text = models.CharField(max_length = 300)    
    ans1_text = models.CharField(max_length = 80, default= "Yes")
    ans1_votes = models.IntegerField(default = 0)
    ans2_text = models.CharField(max_length = 80, default = "No")
    ans2_votes = models.IntegerField(default = 0)
    
    # Store the publication date so that questions are able to be sorted by most
    # recently asked listed first.
    pub_date = models.DateTimeField('date published')
    # Store the total votes on each question so that questions can be sored by
    # popularity.
    votes = models.IntegerField(default = 0)
    
    # Generate a string to represent the Question object
    def __unicode__(self):
        return self.question_text
    
    # Return true or false depending on if the question was asked in the last
    # day.
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    # Specifications for the appearance of the was_published_recently attribute
    # on QSoure's admin site.
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
    # A question manages its own data by tallying new votes via a member
    # function.
    def vote(self, ans_num):
        if(int(ans_num) == 0): 
            self.ans1_votes += 1    
        elif(int(ans_num) == 1): 
            self.ans2_votes += 1
        self.votes = self.ans1_votes + self.ans2_votes

polls/forms.py
from django import forms
from django.core.validators import RegexValidator

# Form that generates the HTML required for a user to input their question and
# answer options.
class QuestionForm(forms.Form):
    alphanumeric = RegexValidator(r'^[\x20-\x7E]*$',
                                  'Only ASCII characters are allowed.')
    question_text = forms.CharField(label='Question', max_length=100, 
                                    validators=[alphanumeric])
    option1 = forms.CharField(label='Option 1', max_length=25, initial="Yes",
                              validators=[alphanumeric])
    option2 = forms.CharField(label='Option 2', max_length=25, initial="No",
                              validators=[alphanumeric])

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.views import generic 
from .models import Question
from .forms import QuestionForm
from django.shortcuts import redirect
from qsource_user.models import *
from django.contrib.auth.models import User

# Main view for the app that loads the question feed according to the user's
# settings.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'    
    # Because get_queryset and get_context_data do not access the request,
    # the relevant user data is stored in a member variable by get().
    user_data = 0

    # Extend the inherited get() function by redirecting if not logged in
    # and saving user's settings.
    def get(self, request, *args, **kwargs):
        if (request.user.is_authenticated() != True):
            return redirectHome()
        else:
            self.user_data = get_data_or_create(request.user)
            return super(IndexView, self).get(self, request, *args, **kwargs)
    
    # Extend inherited get_context_data by adding additional context varibles
    # representing user settings. This allows the HTML to access the user's
    # options for menu display puposes.
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['user_my'] = self.user_data.showMyQuestions
        context['user_local'] = self.user_data.showLocal
        context['user_recent'] = self.user_data.showRecent
        return context

    # Specify the list of questions to display. Choose appropriate sort/filter
    # functions based on user settings.
    def get_queryset(self):        
        if(self.user_data.showRecent):
            if(self.user_data.showMyQuestions):
                return self.get_my_global_recent()
            else:
                return self.get_all_global_recent()
        else:
            if(self.user_data.showMyQuestions):
                return self.get_my_global_popular()
            else:
                return self.get_all_global_popular()
            
    
    # Return the questions asked by this user, most recent first.
    def get_my_global_recent(self):
        my_questions = QuestionsAsked.objects.filter(
            user = self.user_data
        )
        return Question.objects.filter(
            pk__in = [my_q.questionID for my_q in my_questions],
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:10]
    
    # Return the questions asked by this user, most popular first.
    def get_my_global_popular(self):
        my_questions = QuestionsAsked.objects.filter(
            user = self.user_data
        )
        return Question.objects.filter(
            pk__in = [my_q.questionID for my_q in my_questions],
            pub_date__lte=timezone.now()
        ).order_by('-votes')[:10]
    
    # Return the most voted on 10 questions in the database.
    def get_all_global_popular(self):
        return Question.objects.filter( 
            pub_date__lte=timezone.now()
        ).order_by('-votes')[:10]
    
    # Return the most recent 10 questions in the database.
    def get_all_global_recent(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:10]

# View and vote on a single question.
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get(self, request, *args, **kwargs):
        if (request.user.is_authenticated() != True):
            return redirectHome()
        else:
            return super(DetailView, self).get(self, request,*args, **kwargs)
    
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

# Show the results for a single question.
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_context_data(self, **kwargs):
        context = super(ResultsView, self).get_context_data(**kwargs)    
        context['already_answered'] = False
        return context
        
    def get(self, request, *args, **kwargs):
        user_data = get_data_or_create(request.user)
        
        if (not request.user.is_authenticated()
            or not QuestionsAnswered.objects.filter(
                user = user_data, 
                questionID = self.get_object().pk
            ).exists()
        ):
            return redirectHome()
        else:
            return super(ResultsView, self).get(self, request, *args, **kwargs)
    
# Handle POST requests for a new vote. This function is called from form in 
# index.html or detail.html  
def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    user_data = get_data_or_create(request.user)
    ans_num = request.POST.get('ans', -1)
    # Responsibility for modifying data is passed off to the relevant UserData
    # instance.
    success = user_data.answer(p, ans_num)  
    if(success):
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
    else:
        return render( request, 'polls/results.html', {'already_answered':True, 'question':p})

# Handle recieving a request to publish a new question
def GetQuestion(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST or None)
        if form.is_valid():
            # Get info from request
            new_question_text = form.cleaned_data.get("question_text")            
            option1 = form.cleaned_data.get("option1")            
            option2 = form.cleaned_data.get("option2")         
            user_data = get_data_or_create(request.user)
            # Pass off responsibility for new question creation to UserData
            user_data.ask(new_question_text, option1, option2)
            return HttpResponseRedirect('/polls/')
    else:
        form = QuestionForm()
    return render(request, 'question.html', {'form': form})
    
# Return a user's data or, if this is the first time the feed is loaded,
# generate a new UserData object with default settings.
def get_data_or_create(myuser):
    if(hasattr(myuser, 'data') != True):
        #generate a default and proceed
        thisUser = UserData.objects.create(user = myuser)
        thisUser.save()
        return thisUser
        
    else:
        return myuser.data
 
# Change any number of user settings. This function is called from form in 
# index.html
def settings(request):
    # Get all required info from the request.
    opt1_str = request.POST.get('opt1', "")
    opt2_str = request.POST.get('opt2', "")
    opt3_str = request.POST.get('opt3', "")
    thisUser = get_data_or_create(request.user)
    # Change the appropriate settings based on the infor received from the
    # request.
    if(opt1_str == "My"):
        thisUser.showMyQuestions = True
    elif(opt1_str == "All"):
        thisUser.showMyQuestions = False
    if(opt2_str == "Local"):
        thisUser.showLocal = True
    elif(opt2_str == "Global"):
        thisUser.showLocal = False
    if(opt3_str == "Recent"):
        thisUser.showRecent = True
    elif(opt3_str == "Popular"):
        thisUser.showRecent = False        
    thisUser.save()
    return redirect('polls:index', permanent = True)
    
# Redirect a user to the homepage when the user is not logged in.
def redirectHome():
    return redirect('home', permanent = True)

polls/templates/polls/detail.html
{% load staticfiles %}
{% load crispy_forms_tags %}
{% include 'head_css.html' %}
{% include 'navbar.html' %}
{% include "javascript.html" %}

<style>
{% block style %}
.navbar-static-top{
    margin-bottom: 0px !important;
}
 .jumbotron {
    background-color:#0C0547;
    color: #FFF;
 }

{% endblock %}   
</style>

{% block jumbotron %}
<div class="jumbotron">
    <div class="container">
    <div class="row">
        <div class='col-sm-6'>
        

        <h2>{{ question.question_text }}</h2>
        
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}        

        <input type="radio" name="ans" id=1 value=0 />        
        <label for=1>{{ question.ans1_text }}</label><br />

        <input type="radio" name="ans" id=2 value=1 />
        <label for=2>{{ question.ans2_text }}</label><br />
        <p>
        <input class='btn btn-default' type='submit' value='Vote' />        
        </p>
        
        </form>
        </div>        
        </div>
    </div>
 </div>

{% endblock %}

polls/templates/polls/index.html
{% load staticfiles %}
{% load crispy_forms_tags %}
{% include 'head_css.html' %}
{% include 'navbar.html' %}
{% include "javascript.html" %}

<!-- Style specifications to make page design cohesive -->
<style>
{% block style %}
.navbar-static-top{
    margin-bottom: 0px !important;
}
 .jumbotron {
    background-color:#0C0547;
    color: #FFF;   
 }

{% endblock %}

</style>

{% block jumbotron %}
<div class="jumbotron">
  <div class="container">
    <!-- Menu bar: a collapsible row on the Boorstrap grid -->
    <div class="row">
      <div class = "col-sm-8">
        <form action="{% url 'polls:settings' %}" method="post">
        <!-- Security feature prevents calls from outside sources -->
        {% csrf_token %}       
        <div id="menu" class="collapse">
          <!-- Toggle buttons between My Questions and All Questions -->
          <div class="btn-group-vertical" data-toggle="buttons" style = "margin: 20px;">
            <!-- if statements activate buttons according to different settings -->
            {% if not user_my %}
            <label class="btn btn-primary active active">
            {% else %}
            <label class="btn btn-primary">
            {% endif %}
            <input type="radio" name = "opt1" id = 1 value = "All" >All questions</label>
            {% if user_my %}
            <label class="btn btn-primary active active">
            {% else %}
            <label class="btn btn-primary">
            {% endif %}
            <input type="radio" name = "opt1" id = 2 value = "My">My questions</label>
          </div>
          <!-- Toggle buttons between Recent and Popular -->
          <div class="btn-group-vertical" data-toggle="buttons" style = "margin: 20px;">
            {% if user_recent %}
            <label class="btn btn-primary active active">
            {% else %}
            <label class="btn btn-primary">
            {% endif %}
            <input type="radio" name = "opt3" value = "Recent">Recent</label>
            {% if not user_recent %}
            <label class="btn btn-primary active active">
            {% else %}
            <label class="btn btn-primary">
            {% endif %}
            <input type="radio" name = "opt3" value = "Popular">Popular</label>
          </div>
          <div><button type = "submit" class = "btn btn-info" style = "margin-left: 20px;">Apply</button></div>
        </div>
        </form>
      </div>
    </div>
    <div class="row">  
      <div class='col-md-2'></div> 
      <div class='col-md-8'>                 
      <a href="{% url 'polls:question' %}"><h2 style="color:red">Ask a Question</h2></a>
      <link rel="stylesheet" type="text/css" href="{% static 'QSource/custom.css' %}" />
      
      <!-- Display list of questions -->
      {% if latest_question_list %}
          <ul>
      {% for question in latest_question_list %}   
            <!-- Format questions in centered panels -->
            <div class="panel panel-info">
              <div class="panel-heading">
                <p><a href="{% url 'polls:results' question.id %}">{{ question.question_text }}</a></p>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <form action="{% url 'polls:vote' question.id %}" method="post">
                
                {% csrf_token %}    
                <!-- A click on either choice should submit a request -->
                <button type="submit" class="btn btn-info" name="ans" value=0 >{{ question.ans1_text }}</button>
                <button type="submit" class="btn btn-info" name="ans" value=1 >{{ question.ans2_text }}</button>
                </p>
                 
                </form>      
              </div>
            </div>
      {% endfor %}
          </ul>
      {% else %}
          <p>No polls are available.</p>
      {% endif %}
      </div>        
    </div>
  </div>
</div>

{% endblock %}

polls/templates/polls/results.html
{% load staticfiles %}
{% load crispy_forms_tags %}
{% include 'head_css.html' %}
{% include 'navbar.html' %}
{% include "javascript.html" %}

<style>
{% block style %}
.navbar-static-top{
    margin-bottom: 0px !important;
}
 .jumbotron {
    background-color:#0C0547;
    color: #FFF;
 }

{% endblock %}   
</style>

{% block jumbotron %}
<div class="jumbotron">
    <div class="container">
    <div class="row">
        <div class='col-sm-6'>
        {% if already_answered %}
        <div class = "alert alert-warning" >
            <strong>Warning: </strong>You already answered this question. Additional votes are not counted.
        </div>
        {% endif %}
        <h2>{{ question.question_text }}</h2>
        <p>Results</p>

        <ul>

        <li>{{ question.ans1_text }} -- {{ question.ans1_votes}} vote{{ question.ans1_votes|pluralize }}</li>
        <li>{{ question.ans2_text }} -- {{ question.ans2_votes}} vote{{ question.ans2_votes|pluralize }}</li>
        </ul>

        <a href="{% url 'polls:index' %}">Back to feed</a>
        </div>        
        </div>
    </div>
 </div

{% endblock %}